// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Code generation engine for idrisiser.
//
// Takes parsed interface definitions and generates:
//   1. Idris2 modules (.idr) with dependent-type wrappers and proof obligations
//   2. Zig FFI bridge (.zig) exposing proven interfaces via C-ABI
//   3. An .ipkg file for building with the Idris2 compiler
//   4. A build script that orchestrates Idris2 + Zig compilation
//
// The generated Idris2 code uses %default total to ensure all functions
// are provably total (cover all inputs and terminate).

mod idris2;
mod parser;
mod zig_bridge;

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::manifest::Manifest;

/// Generate all artifacts from a manifest.
/// Creates: idris2/<Module>.idr, zig/<name>_ffi.zig, <name>.ipkg, build.sh
pub fn generate_all(manifest: &Manifest, output_dir: &str) -> Result<()> {
    let out = Path::new(output_dir);
    fs::create_dir_all(out.join("idris2"))
        .context("Failed to create idris2 output directory")?;
    fs::create_dir_all(out.join("zig"))
        .context("Failed to create zig output directory")?;

    // Step 1: Parse each interface definition and extract contracts
    let mut all_contracts = Vec::new();
    for iface in &manifest.interfaces {
        let contracts = parser::parse_interface(iface)?;
        println!(
            "  Parsed '{}' ({}) — {} function(s)",
            iface.name,
            iface.format,
            contracts.len()
        );
        all_contracts.push((iface.clone(), contracts));
    }

    // Step 2: Generate Idris2 modules with proof obligations
    for (iface, contracts) in &all_contracts {
        idris2::generate(manifest, iface, contracts, &out.join("idris2"))?;
    }

    // Step 3: Generate Zig FFI bridge
    zig_bridge::generate(manifest, &all_contracts, &out.join("zig"))?;

    // Step 4: Generate .ipkg file for Idris2 build system
    generate_ipkg(manifest, out)?;

    // Step 5: Generate build script
    generate_build_script(manifest, out)?;

    Ok(())
}

/// Generate the .ipkg file for Idris2's build system.
fn generate_ipkg(manifest: &Manifest, output_dir: &Path) -> Result<()> {
    let name = &manifest.project.name;
    let safe_name = name.replace('-', "_");
    let prefix = manifest
        .project
        .module_prefix
        .as_deref()
        .unwrap_or(&safe_name);

    let mut src = String::with_capacity(512);
    src.push_str(&format!("-- Auto-generated by idrisiser for project: {name}\n"));
    src.push_str(&format!("package {safe_name}_verified\n\n"));
    src.push_str("sourcedir = \"idris2\"\n\n");

    // List all generated modules
    src.push_str("modules = ");
    let modules: Vec<String> = manifest
        .interfaces
        .iter()
        .map(|iface| {
            let mod_name = iface.name.replace('-', "_");
            format!("{prefix}.{mod_name}")
        })
        .collect();
    src.push_str(&modules.join(", "));
    src.push('\n');
    src.push('\n');

    // Idris2 options
    src.push_str("opts = \"--total");
    for flag in &manifest.idris2.flags {
        src.push(' ');
        src.push_str(flag);
    }
    src.push_str("\"\n");

    if !manifest.idris2.packages.is_empty() {
        src.push_str("depends = ");
        src.push_str(&manifest.idris2.packages.join(", "));
        src.push('\n');
    }

    let out_path = output_dir.join(format!("{safe_name}_verified.ipkg"));
    fs::write(&out_path, &src)
        .with_context(|| format!("Failed to write .ipkg: {}", out_path.display()))?;
    println!("  Idris2 package: {}", out_path.display());

    Ok(())
}

/// Generate the build script.
fn generate_build_script(manifest: &Manifest, output_dir: &Path) -> Result<()> {
    let name = &manifest.project.name;
    let safe_name = name.replace('-', "_");

    let codegen = manifest
        .idris2
        .codegen
        .as_deref()
        .unwrap_or("chez");

    let mut src = String::with_capacity(1024);
    src.push_str("#!/usr/bin/env bash\n");
    src.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    src.push_str(&format!("# Auto-generated by idrisiser — build script for: {name}\n\n"));
    src.push_str("set -euo pipefail\n\n");

    src.push_str(&format!("echo \"=== idrisiser Build: {name} ===\"\n\n"));

    // Step 1: Compile Idris2 modules
    src.push_str("echo \"[1/3] Compiling Idris2 proofs...\"\n");
    src.push_str(&format!(
        "idris2 --build {safe_name}_verified.ipkg --codegen {codegen}\n\n"
    ));

    // Step 2: Compile Zig FFI bridge
    src.push_str("echo \"[2/3] Compiling Zig FFI bridge...\"\n");
    src.push_str(&format!(
        "zig build-obj -O ReleaseFast zig/{safe_name}_ffi.zig -femit-bin={safe_name}_ffi.o\n\n"
    ));

    // Step 3: Link
    src.push_str("echo \"[3/3] Linking...\"\n");
    src.push_str(&format!(
        "# Link the Idris2 runtime + Zig FFI into a shared library\n"
    ));
    src.push_str(&format!(
        "# zig build-lib -O ReleaseFast {safe_name}_ffi.o -o lib{safe_name}_verified\n\n"
    ));

    src.push_str(&format!("echo \"=== Build complete ===\"\n"));
    src.push_str("echo \"Idris2 proofs compiled and verified.\"\n");

    let out_path = output_dir.join("build.sh");
    fs::write(&out_path, &src)
        .with_context(|| format!("Failed to write build script: {}", out_path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&out_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&out_path, perms)?;
    }

    println!("  Build script:   {}", out_path.display());
    Ok(())
}

/// Build the generated artifacts. Requires `idris2` and `zig` on PATH.
pub fn build(manifest: &Manifest, release: bool) -> Result<()> {
    println!("Building idrisiser project: {}", manifest.project.name);

    let idris2_check = std::process::Command::new("idris2").arg("--version").output();
    if idris2_check.is_err() {
        anyhow::bail!(
            "Idris2 compiler not found on PATH.\n\
             Install: https://idris2.readthedocs.io/en/latest/tutorial/starting.html\n\
             Or use: idrisiser generate  (to generate files without building)"
        );
    }

    let build_dir = Path::new("generated/idrisiser");
    let mut cmd = std::process::Command::new("bash");
    cmd.arg(build_dir.join("build.sh")).current_dir(build_dir);

    if release {
        println!("  Mode: release");
    } else {
        println!("  Mode: debug");
    }

    let status = cmd.status().context("Failed to run build script")?;
    if !status.success() {
        anyhow::bail!("Build failed with exit code: {:?}", status.code());
    }

    Ok(())
}

/// Run the generated verified wrapper.
pub fn run(manifest: &Manifest, args: &[String]) -> Result<()> {
    let safe_name = manifest.project.name.replace('-', "_");
    let binary = format!("generated/idrisiser/build/{safe_name}_verified");

    if !Path::new(&binary).exists() {
        anyhow::bail!(
            "Binary not found: {}. Run 'idrisiser build' first.",
            binary
        );
    }

    println!("Running verified wrapper: {}", manifest.project.name);

    let mut cmd = std::process::Command::new(&binary);
    for arg in args {
        cmd.arg(arg);
    }

    let status = cmd.status().context("Failed to execute verified wrapper")?;
    if !status.success() {
        anyhow::bail!("Wrapper exited with code: {:?}", status.code());
    }

    Ok(())
}
