// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Zig FFI bridge generator for idrisiser.
//
// Generates a Zig source file that bridges between the Idris2-proven interface
// and the user's original implementation. The bridge:
//   - Exports C-ABI functions that Idris2 calls via %foreign
//   - Delegates to user-provided symbols with interface-specific names
//   - Handles type conversions between Idris2 PrimIO types and user types

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use super::parser::FunctionContract;
use crate::manifest::{InterfaceConfig, Manifest};

/// Generate the Zig FFI bridge for all interfaces.
pub fn generate(
    manifest: &Manifest,
    all_contracts: &[(InterfaceConfig, Vec<FunctionContract>)],
    output_dir: &Path,
) -> Result<()> {
    let safe_name = manifest.project.name.replace('-', "_");
    let mut src = String::with_capacity(4096);

    write_header(&mut src, &manifest.project.name)?;
    write_result_type(&mut src)?;

    // For each interface, generate user externs and bridge exports
    for (iface, contracts) in all_contracts {
        let iface_safe = iface.name.replace('-', "_");
        write_interface_bridge(&mut src, &safe_name, &iface_safe, contracts)?;
    }

    write_lifecycle(&mut src, &safe_name)?;
    write_version(&mut src)?;

    let out_path = output_dir.join(format!("{safe_name}_ffi.zig"));
    fs::write(&out_path, &src)
        .with_context(|| format!("Failed to write Zig bridge: {}", out_path.display()))?;
    println!("  Zig FFI bridge: {}", out_path.display());

    Ok(())
}

fn write_header(src: &mut String, name: &str) -> Result<()> {
    writeln!(src, "// SPDX-License-Identifier: PMPL-1.0-or-later")?;
    writeln!(src, "// Auto-generated by idrisiser — do not edit manually.")?;
    writeln!(src, "// Zig FFI bridge for project: {name}")?;
    writeln!(src, "// Regenerate with: idrisiser generate")?;
    writeln!(src)?;
    writeln!(src, "const std = @import(\"std\");")?;
    writeln!(src)?;
    Ok(())
}

fn write_result_type(src: &mut String) -> Result<()> {
    writeln!(src, "// Result codes matching Idris2 ABI")?;
    writeln!(src, "pub const Result = enum(c_int) {{")?;
    writeln!(src, "    ok = 0,")?;
    writeln!(src, "    err = 1,")?;
    writeln!(src, "    invalid_param = 2,")?;
    writeln!(src, "    out_of_memory = 3,")?;
    writeln!(src, "    null_pointer = 4,")?;
    writeln!(src, "    proof_failure = 5,")?;
    writeln!(src, "}};")?;
    writeln!(src)?;
    Ok(())
}

/// Generate the bridge for one interface's contracts.
fn write_interface_bridge(
    src: &mut String,
    project_safe: &str,
    iface_safe: &str,
    contracts: &[FunctionContract],
) -> Result<()> {
    writeln!(src, "// ----------------------------------------------------------------")?;
    writeln!(src, "// Interface: {iface_safe}")?;
    writeln!(src, "// ----------------------------------------------------------------")?;
    writeln!(src)?;

    for contract in contracts {
        let fname = &contract.name;
        let ffi_name = format!("{project_safe}_{fname}");

        // Declare user's original function as extern
        writeln!(src, "// User's implementation of {fname}")?;
        let user_params: Vec<String> = contract
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, zig_type(&p.type_name)))
            .collect();
        let user_ret = zig_type(&contract.return_type);

        if user_params.is_empty() {
            writeln!(
                src,
                "extern fn {iface_safe}_{fname}() callconv(.C) {user_ret};"
            )?;
        } else {
            writeln!(
                src,
                "extern fn {iface_safe}_{fname}({}) callconv(.C) {user_ret};",
                user_params.join(", ")
            )?;
        }

        // Export the bridge function that Idris2 calls via %foreign
        writeln!(src)?;
        writeln!(src, "// Idris2-facing export for {fname}")?;

        // Bridge returns c_int (0 = ok, non-zero = error)
        let bridge_params: Vec<String> = contract
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, zig_prim_type(&p.type_name)))
            .collect();

        if bridge_params.is_empty() {
            writeln!(
                src,
                "export fn {ffi_name}() callconv(.C) u32 {{"
            )?;
            writeln!(
                src,
                "    _ = {iface_safe}_{fname}();"
            )?;
        } else {
            writeln!(
                src,
                "export fn {ffi_name}({}) callconv(.C) u32 {{",
                bridge_params.join(", ")
            )?;
            let call_args: Vec<String> = contract
                .params
                .iter()
                .map(|p| p.name.clone())
                .collect();
            writeln!(
                src,
                "    _ = {iface_safe}_{fname}({});",
                call_args.join(", ")
            )?;
        }

        writeln!(src, "    return 0;  // ok")?;
        writeln!(src, "}}")?;
        writeln!(src)?;
    }

    Ok(())
}

/// Lifecycle functions.
fn write_lifecycle(src: &mut String, safe_name: &str) -> Result<()> {
    writeln!(src, "// ----------------------------------------------------------------")?;
    writeln!(src, "// Lifecycle")?;
    writeln!(src, "// ----------------------------------------------------------------")?;
    writeln!(src)?;

    writeln!(src, "var initialized: bool = false;")?;
    writeln!(src)?;

    writeln!(src, "export fn {safe_name}_verified_init() callconv(.C) c_int {{")?;
    writeln!(src, "    if (initialized) return 1;")?;
    writeln!(src, "    initialized = true;")?;
    writeln!(src, "    return 0;")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    writeln!(src, "export fn {safe_name}_verified_shutdown() callconv(.C) c_int {{")?;
    writeln!(src, "    if (!initialized) return 1;")?;
    writeln!(src, "    initialized = false;")?;
    writeln!(src, "    return 0;")?;
    writeln!(src, "}}")?;
    writeln!(src)?;

    Ok(())
}

/// Version information.
fn write_version(src: &mut String) -> Result<()> {
    writeln!(src, "export fn idrisiser_version() callconv(.C) [*:0]const u8 {{")?;
    writeln!(src, "    return \"0.1.0\";")?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Convert a logical type name to a Zig type.
fn zig_type(t: &str) -> &str {
    match t {
        "Int" | "int" => "c_int",
        "Bits32" | "uint32_t" => "u32",
        "Bits64" | "uint64_t" | "int64_t" => "u64",
        "Nat" | "size_t" => "usize",
        "String" | "string" | "const char*" => "[*:0]const u8",
        "Bool" | "bool" => "bool",
        "Double" | "double" | "float" => "f64",
        "Ptr" | "AnyPtr" | "void*" => "?*anyopaque",
        "()" | "void" | "Unit" => "void",
        "Ptr Bits8" => "[*]const u8",
        _ => "?*anyopaque",
    }
}

/// Convert a logical type to Zig's PrimIO-compatible type.
fn zig_prim_type(t: &str) -> &str {
    match t {
        "Int" | "int" | "Bits32" | "Bool" | "bool" => "u32",
        "Bits64" | "Nat" | "String" | "Ptr" | "AnyPtr" => "u64",
        "Double" | "double" => "f64",
        _ => "u64",
    }
}
